CERNHandlers/cernhandlers/__init__.py
CERNHandlers/cernhandlers/userapi_handler.py
scripts/start_jupyterhub.py

Workaround to allow the oauthrefresher to retrieve the latest oauth token from JupyterHub.
The Jupyter Server Extension that retrieves the user oauth token from JupyterHub (renewed by the Authenticator), assumed that the auth state was visible to the user and it was possible to retrieve it via the API. But this only happens to admins and not to a normal user, thus invalidating our approach. With this change I force the auth state to be visible, even for normal users, while I wait for a clarification with upstream. Ofc others users will only be able to see their tokens and no one else's.
Related to swan-cern/jupyter-extensions#27

CERNHandlers: Show auth state to logged in user

---

KeyCloakAuthenticator/keycloakauthenticator/auth.py

Fix #41
Removes `end_session_endpoint` from the required keys, since if `enable_logout` is false, the `end_session_endpoint` becomes irrelevant. This supports some OIDC provider that does not include `end_session_endpoint` in the openid-configuration endpoint.

Remove end_session_endpoint from required keys

---

KeyCloakAuthenticator/keycloakauthenticator/auth.py

- Do not skip refresh if token is current token is still valid for auth_refresh_age. This conflicts with the upstream logic to refresh only every auth_refresh_age
- Do not fail to refresh if current token is expired
- TODO: Increase Authenticator.auth_refresh_age to prevent duplicate refreshes
Fixes #51

Fix failures to refresh token

---

KeyCloakAuthenticator/README.md
KeyCloakAuthenticator/keycloakauthenticator/auth.py

(The previous PR was reverted, recreating this for iterating on the fix)
- Do not skip refresh if token is current token is still valid for auth_refresh_age. This conflicts with the upstream logic to refresh only every auth_refresh_age
- Do not fail to refresh if current token is expired
- TODO: Increase Authenticator.auth_refresh_age to prevent duplicate refreshes
Fixes #51

Fix failures to refresh token 

---

KeyCloakAuthenticator/README.md
KeyCloakAuthenticator/keycloakauthenticator/auth.py
KeyCloakAuthenticator/setup.py

- Fixes failing logout on kubernetes and new puppet nodes
- Removes `KeyCloakLogoutHandler` in favor of `OAuthenticator.logout_redirect_url` which provides similar functionality
- Removes config `logout_redirect_uri` in favor of the upstream config above
- Pin OAuthenticator version
TODO This needs renaming `logout_redirect_uri` to `logout_redirect_url` in the chart values when updating the image in the chart

Fix logout and pin oauthenticator version

---

KeyCloakAuthenticator/keycloakauthenticator/auth.py

Fixes #42 
Fixes #41 
This update re-uses the parent class fetch method to be able to disable the ssl check in a more maintainable and consistent way. At the same time, this client is asynchronous, which means JH won't block.
Took the opportunity to address an issue that might occur when the IDP is down and we need to restart JH. Without the IDP, JH would block/crash, preventing even logged in users from continue working. Now, it will retry every minute.
New users will see a 500 saying that the config is not ok. Logged in users might be required to re-login, but JH doesn't enforce it (maybe it should...) so they will be able to continue working even if the auth is down (which is an improvement). Once the IDP comes back, the logged in users might not even required to re-login, if their …

Authenticator improvements

---

SwanHub/swanhub/templates/login.html

This page shows a spinner and redirects from javascript to start the oauth process This prevents an unresponsive page when logins are slow.
- Requires Authenticator.auto_login to be disabled (https://github.com/swan-cern/swan-charts/pull/104)
- The only thing different here from puppet infrastructure is that the redirect URL does not include the hostname, as the hostname is not available (from the puppet templating)

Add a loading screen for login page.

---

KeyCloakAuthenticator/keycloakauthenticator/auth.py
KeyCloakAuthenticator/keycloakauthenticator/metrics.py
KeyCloakAuthenticator/keycloakauthenticator/tests/test_auth.py

- Add keycloak_authenticator_tornado_request_duration_seconds metric that measures request times reported by tornado
- Add keycloak_authenticator_tornado_queue_duration_seconds metric that measures time spent in queue for requests
- Log request failures for exchange or refresh requests

Tornado queue & request_time as prometheus metrics

---

KeyCloakAuthenticator/keycloakauthenticator/auth.py
KeyCloakAuthenticator/keycloakauthenticator/metrics.py

At the time of committing, token exchange requests to CERN SSO can have a response time of many seconds (> 10). This commit schedules them in one go for asynchronous execution via `asyncio.gather`, instead of doing them in sequence.
Note that the maximum number of requests done via `self.fetch` that are in flight in a given moment is still limited by Tornado's `AsyncHTTPClient`'s `max_clients` setting.

Parallelize token exchange requests

---

SwanSpawner/swanspawner/swankubespawner.py

The state management methods added by this commit are a temporary fix to store the user_options attribute in the database, so that it is restored after a hub restart. This is intended to fix an error in the post_stop_hook that cleans the Spark services, since that hook checks user_options to see if the user selected a Spark cluster; if the hub has restarted, those user_options are lost and the hook can't do its job.
To be removed when updating to JupyterHub 2.1.0 or higher, which has a fix:
https://github.com/jupyterhub/jupyterhub/pull/3773
The clear_state method is not defined here to clear user_options, since it is invoked when spawning a new user session and it would clear the options that the user specified in the form.

Temporary fix for storing spawner user_options in the database

---

SwanCuller/swanculler/app.py

Since check_ticket.sh calls eos_token.sh, which checks SWAN_DEV.
This goes together with https://github.com/swan-cern/swan-charts/pull/175

Preserve SWAN_DEV when calling check_ticket.sh

---

SwanSpawner/swanspawner/swankubespawner.py
SwanSpawner/swanspawner/swanspawner.py

Since now two images will be supported (Alma9 and CentOS7), the URLs of both need to be configured.
The Alma9 URL is configured via chart settings, and the old CentOS7 image URL is configured via an option of our kubespawner. We make the spawner switch image if centos7 is found in the selected platform.
Goes together with https://github.com/swan-cern/swan-charts/pull/192

Allow to configure an extra URL for a CentOS7-based user image

---

SwanSpawner/swanspawner/swankubespawner.py
SwanSpawner/swanspawner/swanspawner.py
SwanSpawner/swanspawner/templates/options_form_template.html

This makes it possible for users to select the CERN HTCondor pool in the SWAN web form, in the same way they now select Spark clusters.
Additionally, this PR modifies the stop method of the kubespawner to clean the k8s objects that were created when HTCondor was selected. Notice that now the service that opens ports is generic and is shared by Spark and HTCondor.

Offer the option to select the CERN HTCondor pool in the web form

---

SwanSpawner/swanspawner/templates/options_form_template.html

This PR adds:
- A message to the form to advertise the Alma9 platform and JupyterLab.
- The automatic disabling of the Spark cluster if the selected platform is Alma9 (see commit message for details on why).

Changes to the web form template related to Alma9

---

SwanSpawner/swanspawner/swankubespawner.py

It was decided to allow any SWAN user to use the GPU resources available in the SWAN service, granted there are GPUs available to be used.
Therefore, the egroup restriction was removed.

swanspawner: Remove gpu egroup requirement

---

SwanSpawner/swanspawner/swankubespawner.py

This is in the context of providing a dynamic mechanism to check whether a GPU user is a participant of a SWAN event, and if so allocate their session on a certain subset of resources with a configured GPU flavor.
Two configurable parameters are added here for that purpose:
- event_role: name of the auth role that participants of a SWAN event have.
- event_gpu_name: name of the GPU resource assigned to those participants.
Doing this in the pod hook is also more elegant since we will not need anymore to erase the value of the last resource specification that was done.
This goes together with https://github.com/swan-cern/swan-charts/pull/216

Move GPU resource specification to pod hook

---

SwanSpawner/swanspawner/templates/options_form_template.html

This is a temporary change to restrict certain spark clusters to users, based on the platform chosen by the user, while the migration to alma9 is not completed.
The analytix cluster will only be available for the CentOS7 platform and the K8s and QA clusters will only be available for the AlmaLinux9.
It will be reverted once the analytix cluster is fully migrated to alma9 thus completing the migration of all spark clusters to that distribution.

SwanSpawner: Restrict spark clusters to different platforms

---

SwanSpawner/swanspawner/templates/options_form_template.html

If a user selects the NXCALS software stack, keep the spark cluster form field enabled, so that the cluster is propagated to the backend and the session is initialized with spark.

SwanSpawner: Fix nxcals spark cluster not being sent to backend

---

SwanSpawner/swanspawner/swanspawner.py
SwanSpawner/swanspawner/templates/options_form_template.html

Allow users to choose whether they want their local python packages path prepended to the PYTHONPATH variable, so that they are able to use the packages installed on their CERNBox in SWAN notebooks automatically.

SwanSpawner: Add form field to prepend python local packages path

---

SwanSpawner/swanspawner/swanspawner.py

Add log metric to check the number of users that start a session with the classic and jupyterlab interfaces.

SwanSpawner: Add metric to monitor the usage of each interface

---

SwanSpawner/swanspawner/swanspawner.py

This reverts commit f62d99e6418e243c87bf5fd73b081e13050d5081. It is not needed, since a metric is automatically created for any form field when a user setups their session.

Revert "SwanSpawner: Add metric to monitor the usage of each interface"

---

SwanHub/swanhub/handlers_configs.py
SwanHub/swanhub/spawn_handler.py
SwanSpawner/swanspawner/swandockerspawner.py
SwanSpawner/swanspawner/swankubespawner.py
SwanSpawner/swanspawner/swanspawner.py
SwanSpawner/swanspawner/templates/options_form_template.html

Result:
Spawner can now launch custom environments through its web interface.
Developments:
Thanks to changes on SwanSpawner and SwanHub, its now possible to avoid having to install all LCG packages and provide a specific amount of packages through cernbox/eos path or git repo containing a requirements.txt file.
This new custom virtual environment can then be launched by a generic python venv or a acc-py stack.
The user gets redirected to /customenv where the process details are shown up in real time, so the users is able to keep up with its going on under the hood. In the end, a completely empty custom environment (just with the provided packages) gets ready for the user to work on.

New feature for custom environments

---

SwanSpawner/swanspawner/swanspawner.py

When input fields are empty, the value that is sent to backend is an empty string and not a None value. This PR fix that verification

Fix on if statement regarding empty repository error

---

SwanSpawner/swanspawner/templates/options_form_template.html

This is done for allowing the git url pattern to accept `.git` extension

swanspawner: fix on git url pattern

---

SwanHub/swanhub/handlers_configs.py
SwanHub/swanhub/spawn_handler.py
SwanSpawner/swanspawner/swanspawner.py
SwanSpawner/swanspawner/templates/options_form_template.html

Spawner can now use GET for getting the same arguments it gets through POST requests. With this, an URL that includes a `notebook` argument can open it after launching a session with the remaining specified parameters. If it is a customenv session, it just forwards the `notebook` argument to the SwanCustomEnvironments extension and this will take care of the rest.

swanhub, swanspawner: New feature for notebook arguments

---

SwanHub/setup.py

Because of https://github.com/jupyterhub/jupyterhub/issues/4629.

[SwanHub] Update jupyterhub version to 4.1.6

---

SwanHub/swanhub/handlers_configs.py
SwanHub/swanhub/spawn_handler.py
SwanSpawner/swanspawner/swanspawner.py
SwanSpawner/swanspawner/templates/options_form_template.html

Swanhub can now also forward `conda` builder option through URL param to `SwanCustomEnvironments` extension

swanhub: new `conda` builder option

---

SwanSpawner/swanspawner/swanspawner.py

The alma9 image uses /home/user and not /scratch/user anymore.

[SwanSpawner] Fix local home path

---

SwanSpawner/swanspawner/swanspawner.py

Specify 'none' for older lcg releases when spark-cluster option gets disabled

swanspawner: Fix bug for not specified spark param

---

SwanSpawner/swanspawner/swanspawner.py
SwanSpawner/swanspawner/templates/options_form_template.html

Fix visual effects of the checkbox when the user provides the value via query args or changes form between software_source
`file` options is used for opening a file when the session gets started. It works for both lcg and customenvs sessions.

swanspawner: Fix `use-jupyterlab` and recover `file`

---

SwanSpawner/swanspawner/swandockerspawner.py

The webhdfsbrowser extension is no longer deployed in the new AlmaLinux 9 user image, so the code snippets that were removed are no longer useful

Remove code related to webhdfs

---

SwanHub/swanhub/handlers_configs.py
SwanHub/swanhub/spawn_handler.py
SwanSpawner/swanspawner/swanspawner.py
SwanSpawner/swanspawner/templates/options_form_template.html

Only git repositories are allowed from now on

swanspawner, swanhub: Remove `repo_type` option

---

SwanSpawner/swanspawner/templates/options_form_template.html

NXCals selector was not being updated with its value passed as query argument because the moment it was being fulfilled, the options weren't loaded yet.

swanspawner: Fix nxcals selector

---

SwanSpawner/swanspawner/templates/options_form_template.html

- New button in the form for gathering all the selected options and generating a URL that fills it automatically
- New extendable section for extra options (so far only includes File Path field)
[URL here](https://rhenriqu-k8s.cern.ch/hub/spawn?software_source=customenv&use-jupyterlab=true&cores=4&memory=10&clusters=hadoop-nxcals&builder=accpy%3A2023.06&repository=https%3A%2F%2Fgitlab.cern.ch%2Frhenriqu%2Fgitlab_req&file=requirements.txt)

Swan on tn generate url

---

SwanHub/swanhub/spawn_handler.py
SwanHub/swanhub/templates/spawn_conflict.html
SwanSpawner/swanspawner/templates/options_form_template.html

Hide breakline properly, in order to keep the space balanced between fields
After opening a new tab on top of a running session: spawn-pending -> dialog modal to allow the user to access the current session or shut it down
If the current session is lcg: forward the user directly to the JupyterLab
If it is a customenv: forward him to the extension page in order to get the creation progress of the environment
*\*before\**
*\*currently\**

Swan on tn preventions

---

SwanHub/swanhub/templates/home.html
SwanHub/swanhub/templates/spawn_conflict.html

Change info message for `spawn_conflict` page
Reuse query arguments for redirecting the user back to the form with all options specified initially

swanhub: Fix redirect back to form

---

SwanSpawner/swanspawner/swanspawner.py

Add error at the top of the user form:

Display error on session start if env script path does not exist

---

SwanHub/swanhub/handlers_configs.py
SwanHub/swanhub/spawn_handler.py
SwanHub/swanhub/templates/spawn.html
SwanSpawner/swanspawner/swanspawner.py
SwanSpawner/swanspawner/templates/options_form_template.html

When filling this checkbox, the user will be redirected to another cluster that is exposed to the TN, preserving all of the originally specified url params.
Also, when `tn_enabled` is defined, the value specified in `spawn.html` for `use-tn` checkbox needs to be preserved.

swanspawner: New option to redirect to the TN

---

SwanHub/swanhub/spawn_handler.py
SwanSpawner/swanspawner/templates/options_form_template.html

For GET request, take the value from the `query_arguments` and check the validity of `software_source` and `use-tn`. For POST requests, check their values from `body_arguments`. This is done before checking any other value, considering these two have direct implications on how sessions are created.

swanhub: Pre validate mandatory arguments

---

SwanSpawner/swanspawner/templates/options_form_template.html

Frontend failed if both `lcg_optons` and `customenv_options` weren't specified, leaving all fields blank. Now it ignores non specified values, avoid errors and filling only the provided ones.

swanspawner: Prevent against not specified `customenv_options`

---

SwanSpawner/swanspawner/swandockerspawner.py

Currently the Spark on k8s cluster does not have the correct configuration for using Hadoop.
The path to the configuration file for Hadoop is incorrect. This is to fix it.

Fix path for k8s SWAN config script

---

SwanHub/swanhub/templates/spawn.html

When the template is rendered, first the page is loaded, then is the form. For this reason, the checkbox must be ticked only when the modal is ready, when the `use-tn` can be correctly found. A warning message is also added if it doesn't get found, for debugging purposes.

swanhub: Tick checkbox when form is loaded

---

SwanHub/swanhub/spawn_handler.py

This change makes the `SwanContents` extension able to open the downloaded project either on ClassicUI or JupyterLab, depending on the given checkbox value

swanhub: Append `use-jupyterlab` value to the `next_url` call

---

SwanHub/swanhub/templates/spawn_conflict.html

The use of `{{base_url}}` may sometimes inject `/hub/spawn` as `next_url`, which can lead to 404 errors. This implementation clears that up, ensuring it always goes to the given `next_url`

swanhub: Fix user redirection

---

KeyCloakAuthenticator/keycloakauthenticator/auth.py

As of Keycloak 26.2, "Standard token exchange V2" is an officially supported feature. As part of the specification for this feature, the field `subject_token_type` is a required header in the exchange request (and must be `urn:ietf:params:oauth:token-type:access_token`): https://www.keycloak.org/securing-apps/token-exchange#_standard-token-exchange-request . If `subject_token_type` is absent, Keycloak throws an error and rejects the exchange request.
This commit adds the correct subject_token_type field to the request header to allow use of the new standard token exchange V2.

KeyCloakAuthenticator: Add "subject_token_type" to token exchange

---

SwanSpawner/swanspawner/swankubespawner.py

With these changes, alongside with the ones in the charts (click [here](https://github.com/swan-cern/swan-charts/pull/394)), the CI used for updating the swan-cern version can be reused also for swan-accpy.

swanspawner: Redefinition of `accpy_image` for making the CI process easier
