swan-cern/jupyterhub-extensions

SwanSpawner/swanspawner/swanspawner.py, jupyterhub_config.py
tested sourcing a script with sleep 30 
thanks to @prasanthkothuri  for helping me with the spare node :)
=> [UCA-432] added extended timeout when user is providing custom script

templates/page.html
swan-cern/jupyter-extensions#40
=> Remove reference to Jira from the footer

SwanSpawner/swanspawner/swankubespawner.py
Fixes #19
This fixes the problem we saw in swan-k8s. I haven't tested.
=> Do not hardcode user selections in the spawner

KeyCloakAuthenticator/README.md, KeyCloakAuthenticator/keycloakauthenticator/auth.py, SwanSpawner/swanspawner/swanspawner.py
This PR allows exchanging our SWAN oauth token for tokens of other services (like EOS and CERNBox).
Closes #29
=> Exchange tokens

KeyCloakAuthenticator/README.md, KeyCloakAuthenticator/keycloakauthenticator/auth.py, KeyCloakAuthenticator/setup.py
=> check JWT token signature and use PyJWT 2

KeyCloakAuthenticator/README.md, KeyCloakAuthenticator/keycloakauthenticator/auth.py
Replace accepted_roles by allowed_roles and make it a list
Validate callables
Closes #35 
Replaces #36
=> KeycloakAuthenticator: configurable roles retrieval

SwanHub/swanhub/handlers_configs.py, SwanHub/swanhub/spawn_handler.py, SwanHub/swanhub/templates/home.html
Readding an `await` that I had removed by mistake
Removing the #changeconfig query param because we don't have swanrc anymore
=> Swanhub041

KeyCloakAuthenticator/keycloakauthenticator/auth.py
=> Log token exchange failure

.github/workflows/release.yml, README.md
Copied the action from `jupyter-extensions`. Please use this instead to release.
=> Automatic release actioon

SwanNotificationsService/Dockerfile, SwanNotificationsService/README.md, SwanNotificationsService/setup.py, SwanNotificationsService/swannotificationsservice/app.py, SwanNotificationsService/swannotificationsservice/service.py
=> WIP Notifications

KeyCloakAuthenticator/keycloakauthenticator/auth.py
Decorators do not work in measuring async functions
=> Fix Metrics: Use context manager blocks instead of function decorators 

SwanSpawner/swanspawner/templates/options_form_template.html
Minor update to configuration pop-up window messages.
=> Minor update to configuration pop-up window messages.

SwanSpawner/swanspawner/swankubespawner.py
As a fraction of the memory limit that the user specified when launching their session.
Goes together with https://github.com/swan-cern/swan-charts/pull/134
=> SwanKubeSpawner: dynamically set memory request (guarantee) of user pods

SwanSpawner/swanspawner/swankubespawner.py
Plus move one setting from OpenCL from the charts to the spawner, to slim down the hooks in the charts.
=> Remove NVIDIA settings that were not necessary / desirable

SwanSpawner/swanspawner/swanspawner.py
`SOFTWARE_SOURCE` is used for the script on `swan` image layer to know if it has to configure lcg or not
=> New environment variable defined by spawner

SwanSpawner/swanspawner/swankubespawner.py
Using accpy_image for all customenv sessions (temporary solution)
=> swanspawner: New accpy_image configuration

SwanHub/swanhub/spawn_handler.py, SwanHub/swanhub/templates/spawn_conflict.html, SwanSpawner/swanspawner/templates/options_form_template.html
- Certain software stacks have their own resources and platforms. So, `adjust_form()` needs to be called for the selected lcg
- Change input background color for invalid repos in url args
- Simplify error message for invalid software source in url args
- Simplification of `if` statements
=> swanspawner: Fix and simplify form filling with url args

SwanHub/swanhub/templates/spawn.html, SwanSpawner/swanspawner/templates/options_form_template.html
Implement opening a file also for classic UI
Adapting description of file feature to lcg and custom envs
Deal with wrongly passed url args when starting a session - When a attribute is wrongly define and a session is attempted to start with it, trigger an error message that warns the user to fix the value
=> Fixes from Diogo suggestions

SwanHub/swanhub/handlers_configs.py, SwanHub/swanhub/spawn_handler.py, SwanHub/swanhub/templates/home.html, SwanHub/swanhub/templates/spawn.html, SwanHub/swanhub/templates/spawn_conflict.html, SwanSpawner/swanspawner/swankubespawner.py, SwanSpawner/swanspawner/swanspawner.py, SwanSpawner/swanspawner/templates/options_form_template.html
This PR includes all the visual and logical modifications to the form, in order to configure a session using custom environemnts instead of a LCG software stack, and includes the possibility to generate URLs base on the current configuration, filling, by this way, the requirements imposed by the Swan-on-TN project.
=> Swan-on-TN

SwanCuller/swanculler/app.py
The SSO team only block the accounts and not identities except for security emergencies where the security team can actually block the whole identity.
=> [SwanCuller]: fix - change authzapi url and query to check for blocked users
